### ISSUE TITLE
Error when try install winterjs on macos Sonoma

### ISSUE THREAD

**Issue by architectureman** [wasmerio/winterjs#59]
error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/wasmerio/mozjs.git?branch=wasi-gecko#91349dc0)

**Comment by Arshia001** [comment]
Hi @architectureman, thanks for reporting this! To be able to investigate the issue, we will need the full log output from your build, including the output from the build steps for `mozjs_sys`.

**Comment by folivi** [comment]
Hi! I'm having the same issue.

Here is the error log:

error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/wasmerio/mozjs.git?branch=wasi-gecko#7f760f85)`

Caused by:
  process didn't exit successfully: `/var/folders/sy/ll_0l4dn4g38_mzt9ds81dtm0000gn/T/cargo-installBwFJUm/release/build/mozjs_sys-09553b7a0110c3c1/build-script-build` (exit status: 101)
  --- stdout
  cargo:outdir=/var/folders/sy/ll_0l4dn4g38_mzt9ds81dtm0000gn/T/cargo-installBwFJUm/release/build/mozjs_sys-621216e2bec8c898/out/build
  [[ '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/configure -ot '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/configure.in ]] && touch '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/configure || true
  [[ '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/old-configure -ot '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/old-configure.in ]] && touch '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/old-configure || true
  ! [[ '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/configure.in -ot '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/configure ]] && touch '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/configure || true
  ! [[ '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/old-configure.in -ot '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/old-configure ]] && touch '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/old-configure || true
  if [[ '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/configure -nt config.status ]] ; then \
  	  CC="cc" CFLAGS="" \
  	  CPP="cc -E" CPPFLAGS="-I/Users/dev1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/encoding_c_mem-0.2.6/include " \
  	  CXX="c++" CXXFLAGS="-stdlib=libc++" \
  	  AS="" AR="ar" \
  	  '/Users/dev1/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys'/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --with-intl-api --build-backends=RecursiveMake --enable-js-streams || (cat config.log && exit 1) ; \
  	fi
  Using Python 3.10.9 from /usr/local/opt/python@3.10/bin/python3.10
  Creating local state directory: /Users/dev1/.mozbuild/srcdirs/mozjs-edc904cf726b
  Site not up-to-date reason: "/Users/dev1/.mozbuild/srcdirs/mozjs-edc904cf726b/_virtualenvs/build" does not exist
  
The last message:

  
  --- stderr
  gmake: *** No targets specified and no makefile found.  Stop.
  DEBUG: Executing: `/usr/bin/cc -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk -mmacosx-version-min=11.0 -std=gnu99 -Wl,--version`
  DEBUG: Executing: `/usr/bin/cc -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk -mmacosx-version-min=11.0 -std=gnu99 -fuse-ld=lld -Wl,--version`
  ERROR: Failed to find an adequate linker
  make: *** [maybe-configure] Error 1
  thread 'main' panicked at /Users/folivif/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/7f760f8/mozjs-sys/build.rs:272:5:
  assertion failed: result.success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `winterjs v1.2.0 (https://github.com/wasmerio/winterjs#a65dc452)`, intermediate artifacts can be found at `/var/folders/sy/ll_0l4dn4g38_mzt9ds81dtm0000gn/T/cargo-installBwFJUm`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by syrusakbary** [comment]
We added macOS builds into CI to verify that everything builds properly, you can now also download the generated binary artifacts of WinterJS for each platform/chipset

![image](https://github.com/wasmerio/winterjs/assets/188257/d47f3af5-1036-450e-ad39-815ce9e53784)
